---
- name: Update packages on Linux systems
  hosts: all
  become: yes  # To escalate privilege to root (sudo)
  tasks:
    - name: Update package cache and upgrade packages
      package:
        name: "*"
        state: latest

